# fly.toml app configuration file generated for jiralite-st on 2025-04-20T17:57:01+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jiralite-st'
primary_region = 'iad'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "512mb"
